package com.example.demo.repository;

import com.example.demo.model.Exercise;
import com.example.demo.model.User;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
@Transactional // Face rollback după fiecare test ca să nu-ți murdărească baza din SSMS
@DisplayName("SSMS Database Integration Tests - Assignment 3")
class DatabaseIntegrationTest {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private ExerciseRepository exerciseRepository;

    private User testUser;

    @BeforeEach
    void setUp() {
        // Creăm un utilizator de test
        testUser = new User();
        testUser.setName("Test Stelian");
        testUser.setEmail("test.stelian@example.com");
        testUser.setPassword("password123");
        testUser = userRepository.save(testUser);
    }

    @Test
    @DisplayName("Test Persistence: Save User and Exercise in SSMS")
    void testSaveUserAndExercise() {
        // 1. Verificăm salvarea utilizatorului
        assertNotNull(testUser.getId(), "User ID should be generated by SSMS");

        // 2. Creăm și salvăm un exercițiu legat de user
        Exercise ex = new Exercise();
        ex.setName("SSMS Bench Press");
        ex.setMuscle("Chest");
        ex.setWeight(100);
        ex.setReps(10);
        ex.setSets(3);
        ex.setDuration(30);
        ex.setCreatedBy(testUser);

        Exercise savedEx = exerciseRepository.save(ex);

        // 3. Verificări
        assertNotNull(savedEx.getId(), "Exercise ID should be generated by SSMS");
        assertEquals("SSMS Bench Press", savedEx.getName());
        assertEquals(testUser.getId(), savedEx.getCreatedBy().getId(), "Relationship 1-to-Many should work");
    }

    @Test
    @DisplayName("Test Constraints: Unique Email Validation")
    void testUniqueEmailConstraint() {
        User duplicateUser = new User();
        duplicateUser.setName("Andrei");
        duplicateUser.setEmail("test.stelian@example.com"); // Același email ca în setUp
        duplicateUser.setPassword("pass123");

        // Trebuie să arunce o eroare de la baza de date (DataIntegrityViolationException)
        assertThrows(org.springframework.dao.DataIntegrityViolationException.class, () -> {
            userRepository.saveAndFlush(duplicateUser);
        }, "SSMS should reject duplicate emails (3NF integrity)");
    }

    @Test
    @DisplayName("Test Query: Statistics by Muscle Group")
    void testMuscleGroupStatistics() {
        // Adăugăm un exercițiu de spate
        Exercise ex = new Exercise();
        ex.setName("Deadlift");
        ex.setMuscle("Back");
        ex.setWeight(150);
        ex.setReps(5);
        ex.setSets(3);
        ex.setDuration(20);
        ex.setCreatedBy(testUser);
        exerciseRepository.save(ex);

        List<Object[]> stats = exerciseRepository.countByMuscleGroup();

        assertFalse(stats.isEmpty(), "Statistics query should return results");
        assertTrue(stats.stream().anyMatch(row -> row[0].equals("Back")), "Should find 'Back' group");
    }
}