spring.application.name=NextRep

# Conexiunea directă scrisă în fișier
spring.datasource.url=jdbc:postgresql://stelian:CZYqy2EpWVz6Rmr1LS42sN7FQZFAbfsv@dpg-d8ggqartqb8s73bj7kag-a.frankfurt-postgres.render.com/nextrep?sslmode=require
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=stelian
spring.datasource.password=CZYqy2EpWVz6Rmr1LS42sN7FQZFAbfsv

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Portul din container pe care îl va citi Render
server.port=8080
server.address=0.0.0.0

jwt.secret=your_secret_key_that_must_be_at_least_32_characters_long_for_HS256_algorithm
jwt.expiration=3600000
